# Generated by Django 3.1.7 on 2021-03-16 18:19

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    Answer = apps.get_model("assessment", "Answer")
    db_alias = schema_editor.connection.alias
    Answer.objects.using(db_alias).all().delete()


def reverse_func(apps, schema_editor):
    """ not reversable """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_user_raw_password'),
        ('assessment', '0001_initial'),
    ]

    operations = [

        migrations.RunPython(forwards_func, reverse_func),

        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='answer',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.subject'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.teacher'),
        ),
    ]
