# Generated by Django 3.1.7 on 2021-04-13 04:09

import assessment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_auto_20210405_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='variant',
            field=models.CharField(max_length=255, validators=[assessment.models.check_json]),
        ),
    ]
