# Generated by Django 3.1.7 on 2021-04-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_auto_20210413_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quick_mode',
            field=models.BooleanField(default=False),
        ),
    ]
