# Generated by Django 3.1.7 on 2021-03-01 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='module',
        ),
        migrations.AddField(
            model_name='tutor',
            name='module',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='booking.module'),
            preserve_default=False,
        ),
    ]
