# Generated by Django 3.1.7 on 2021-03-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_id', models.CharField(max_length=255, unique=True)),
                ('day', models.CharField(choices=[('11111', 'Every day'), ('100000', 'Monday'), ('010000', 'Tuesday'), ('001000', 'Wednesday'), ('000100', 'Thursday'), ('000010', 'Friday'), ('000001', 'Saturday')], default='100000', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_id', models.CharField(max_length=255, unique=True)),
                ('term', models.CharField(choices=[('11', 'Whole year'), ('10', 'Term 1'), ('01', 'Term 2')], default='10', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(choices=[('111111111111111', 'All weeks'), ('100000000000000', 'Week A'), ('010000000000000', 'Week B'), ('001000000000000', 'Week C'), ('000100000000000', 'Week D'), ('000010000000000', 'Week E'), ('000001000000000', 'Week F'), ('000000100000000', 'Week G'), ('000000010000000', 'Week H'), ('000000001000000', 'Week I'), ('000000000100000', 'Week J'), ('000000000010000', 'Week K'), ('000000000001000', 'Week L'), ('000000000000100', 'Week M'), ('000000000000001', 'Week O'), ('000000000000010', 'Week N')], default='100000000000000', max_length=15)),
                ('week_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
