# Generated by Django 3.1.7 on 2021-03-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='period',
            field=models.CharField(choices=[('1', '9:00-10:00'), ('2', '10:20-11:20'), ('3', '12:00-13:00'), ('4', '13:20-14:20'), ('5', '14:40-15:40'), ('6', '16:00-17:00')], default='1', max_length=1),
        ),
    ]
