# Generated by Django 3.1.7 on 2021-03-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210325_0818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='group',
            new_name='groups',
        ),
    ]
