# Generated by Django 3.1.7 on 2021-04-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210409_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='short',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='color',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='short',
            field=models.CharField(max_length=255),
        ),
    ]
