# Generated by Django 3.1.7 on 2021-03-01 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210301_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='module',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to='booking.module'),
        ),
    ]
