# Generated by Django 3.1.7 on 2021-03-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_room_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='module',
        ),
        migrations.AddField(
            model_name='tutor',
            name='module',
            field=models.ManyToManyField(to='booking.Module'),
        ),
    ]
