# Generated by Django 3.1.7 on 2021-03-25 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20210325_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='classroom',
            field=models.ForeignKey(blank=True, default='classroom', null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.classroom'),
        ),
    ]
