# Generated by Django 3.1.7 on 2021-03-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20210317_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='education_year',
        ),
        migrations.RemoveField(
            model_name='user',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='user',
            name='raw_password',
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.IntegerField(default=1),
        ),
    ]
