# Generated by Django 3.1.7 on 2021-04-13 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20210412_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('term', models.CharField(max_length=25)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.teacher')),
            ],
        ),
    ]
