# Generated by Django 3.1.7 on 2021-03-05 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20210304_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='module',
        ),
        migrations.CreateModel(
            name='TutorModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.module')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.tutor')),
            ],
            options={
                'unique_together': {('tutor', 'module')},
            },
        ),
        migrations.AddField(
            model_name='tutor',
            name='modules',
            field=models.ManyToManyField(related_name='tutors', through='booking.TutorModule', to='booking.Module'),
        ),
    ]
