# Generated by Django 3.1.7 on 2021-04-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
        migrations.AddField(
            model_name='teacher',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=3),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TeacherSubject',
        ),
    ]
