# Generated by Django 3.1.7 on 2021-04-19 05:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20210419_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='from_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='to_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
