# Generated by Django 3.1.7 on 2021-04-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20210419_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attended_questionnaire',
            field=models.IntegerField(default=0),
        ),
    ]
