# Generated by Django 3.1.7 on 2021-04-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_user_attended_questionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='lesson_link',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
