# Generated by Django 3.1.7 on 2021-04-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_teacher_lesson_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='meeting_credentials',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
